### ISSUE TITLE
V3 Design - VFAN?

### ISSUE THREAD

**Issue by ShockStruck** [LaskaKit/ESP-Vindriktning#8]
Hello,

Just received 6 PCB's of the V3 varient from JLPCB. Couldn't help but notice that there's no SMD component where labeled "V FAN" 5v/3.3v. is there supposed to be something there? I looked at v2 Schematics, V3 bom and V3 cpl, it appears to not be mentioned . Also noticed that when using the code provided for ESPHome, the lights do not illuminate on the unit. I have found code from bruxy70 on GitHub that resolved this issue.

I should mention that I desoldered the sensor connector from my IKEA boards and placed them into the V3 Board as the connector was backordered.

Thanks for all your help!

![PXL_20221230_231434485](https://user-images.githubusercontent.com/30438286/210117392-c25b406f-7dbd-464e-a86e-3372038f0123.jpg)
![PXL_20221230_231443538 MP](https://user-images.githubusercontent.com/30438286/210117398-606aed6b-0b25-47d8-ba82-8dae2251fbc5.jpg)

**Comment by Konstantin-G** [comment]
The version 3.0 board is not yet in production and has not been tested. She got onto GitHub by mistake.
V_FAN is a jumper that allows you to power the fan with a voltage of 5V or 3.3V. At 3.3V, the fan has lower rpm and less noise. It has not yet been tested whether switching to 3.3V has any effect on the accuracy of the measurement. By default, the jumper is set to 5V. So there is no need to deal with it.
I have been testing the ESPHome code here for a long time and there is no problem with it. The LEDs are only activated after the sun rises and turn off at sunset. It receives this data from Homeassistant. It might want to fine-tune min_brightness, because at the default value of 0.1 the LED does not light up. We have not yet had the opportunity to examine it in detail and possibly modify it.
